### ISSUE TITLE
Testing on AppImage

### ISSUE THREAD

**Issue by luzpaz** [mnesarco/FreeCAD_ExtMan#1]
Thank you for working on this!  

So...unable able to test ExtMan using the [AppImage](https://wiki.freecadweb.org/AppImage). I followed the installation instructions for [git](https://github.com/mnesarco/FreeCAD_ExtMan#git) and restarted. When I ran the Addon Manager it showed the current one and not your ExtMan.

When starting the AppIMage from the CLI, I see a peculiar warning though that I'm not used to (thought it may be related):  
`Tried to run Gui::Application::initApplication() twice!`

My About info:  
```
OS: Manjaro Linux (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.21329 (Git) AppImage
Build type: Release
Branch: master
Hash: 2330eef823b32ac412d839031cc174353a76b013
Python version: 3.8.2
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)
```

**Comment by mnesarco** [comment]
Hi @luzpaz 

> When I ran the Addon Manager it showed the current one and not your ExtMan.

This project has nothing to do with Addon Manager. This is an independent Workbench, so you have to activate it from the Workbenches selector. Maybe at some future it will replace the Addon Manager.

> Tried to run Gui::Application::initApplication() twice!

I got this warning too with AppImage, but it is not blocking. I don't know where it comes from since i never call  Gui::Application::initApplication().

**Comment by luzpaz** [comment]
My bad, didn't realize this was a workbench :blush:  
Looks great!

**Comment by mnesarco** [comment]
@luzpaz please be sure you have the latest version, i have fixed something few minutes ago.

**Comment by luzpaz** [comment]
@mnesarco thanks for the heads up, which reminds me, will the workbench eventually report that addons have updates ?

**Comment by mnesarco** [comment]
@luzpaz 
> will the workbench eventually report that addons have updates ?

That's the idea, but i am not there yet.

**Comment by vocx-fc** [comment]
@luzpaz See the forum posts in [Add ons manager - development and bugs topic](https://forum.freecadweb.org/viewtopic.php?f=10&t=37394&start=190#p404699).

At the moment you have to use the current Addon Manager to install this new "Extension manager". It doesn't replace the current one, at least not at the moment.

Also, the message about `Gui::Application::initApplication()` is independent of this. This message started appearing about a week ago. It's some change that the C++ guys did, Werner maybe, but it seems to be harmless.
