### ISSUE TITLE
resources missing when installed with pip

### ISSUE THREAD

**Issue by looooo** [mnesarco/FreeCAD_ExtMan#2]
I installed with `pip install . --no-deps` and see missing resources. Maybe you need to include them in  `MANIFEST.in`. Not sure if the `manifest.ini` is for the same purpose.

```
Cannot find icon: /home/lo/miniconda3/envs/freecad/lib/python3.8/site-packages/Resources/icons/ExtManWorkbench.svg
```

```
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/home/lo/miniconda3/envs/freecad/lib/python3.8/site-packages/Resources/html/index.html'
```

**Comment by mnesarco** [comment]
Hi @looooo , thank you. I don't know how to include it properly. I will add a MANIFEST.in with   `recursive-include Resources * ` But i have no idea if it works as expected. Any suggestion about this will be great.

Commit: 841c5d13aa54fedeb760018228d1917e1c2012c3

**Comment by looooo** [comment]
yes I think this should do the job. But I guess it's better to keep the resources inside the module, otherwise one might run into name-clashes. Is it possible to move Resources inside `FreeCAD_ExtMan/freecad/extman/`?

**Comment by mnesarco** [comment]
@looooo 
> yes I think this should do the job. But I guess it's better to keep the resources inside the module, otherwise one might run into name-clashes. Is it possible to move Resources inside `FreeCAD_ExtMan/freecad/extman/`?

Interesting, does it means that the recommended structure for Extensions require to put everything inside the package?. It has a lot of sense, I just want to be sure that it is the correct structure as practically all Workbenches have a Resources folder in root.

I am working on a technical document with the specs for FreeCAD Extensions development. It is based on your FPE plus some metadata in a manifest file to enhance indexing and discoverability.

**Comment by looooo** [comment]
> Interesting, does it means that the recommended structure for Extensions require to put everything inside the package?. It has a lot of sense, I just want to be sure that it is the correct structure as practically all Workbenches have a Resources folder in root.

There are 2 different ways to extend freecad:
1. Old way with InitGui.py
2. New way with init_gui.py

The advantages of the second is that it is installable with pip and the addonmanager + some other advantages like avoiding name-clashes.

If you install with pip it makes a lot of sense to add the resources inside the package. I didn't run in any issues on the freecad side so far. So therefore I would recommend it.

**Comment by mnesarco** [comment]
> There are 2 different ways to extend freecad:
> 
>     1. Old way with InitGui.py
> 
>     2. New way with init_gui.py
> 
> 
> The advantages of the second is that it is installable with pip and the addonmanager + some other advantages like avoiding name-clashes.
> 
> If you install with pip it makes a lot of sense to add the resources inside the package. I didn't run in any issues on the freecad side so far. So therefore I would recommend it.

@looooo very good, In the ideal world we should deprecate the Old way and promote only the new way. One way to push the change is to only accept Extensions with the new Layout in the new Extension Manager, some times is better to break backward compatibility, in that case, old extensions can be installed manually anyway but only updated extensions can be managed by the Extension Manager. The only missing part in the "New way layout" is a well defined manifest (FreeCAD specific) with Extension Metadata and I am working in a proposal for it.

The other approach is to try to maintain both layouts at expense of quality.

As I can see, it is very easy to migrate any workbench from the previous layout to the new one and everyone wins.  So therefore I would recommend a hard deprecation of the old way.

I will soon submit a technical document with:

1. FreeCAD Extension Development Spec.
2. Migration Guide.
3. Best practices (maybe)

**Comment by mnesarco** [comment]
I keep this open for discussion

**Comment by looooo** [comment]
> @looooo very good, In the ideal world we should deprecate the Old way and promote only the new way.

Yes, but the world is far from ideal ; ). There are some difficulties with internal workbenches (c++). For sure in theory it's possible but complicated. So better use the new workbech-style (or namespace workbenches like currently suggested) wherever possible and hope people at one point see the advantages and working towards consistency. 


> I will soon submit a technical document with:
> 
> 1. FreeCAD Extension Development Spec.
> 2. Migration Guide.
> 3. Best practices (maybe)

That sounds promising. There are also others working on this topic (@gbroques).

**Comment by mnesarco** [comment]
@looooo yes I am aware of some forum threads about this topic and I am following it. In the mean time it would be great if you can confirm if latest changes make this Extension working with pip as expected. You are the authority about that.

**Comment by looooo** [comment]
works, thanks for fixing.

**Comment by gbroques** [comment]
> > @looooo very good, In the ideal world we should deprecate the Old way and promote only the new way.
> 
> Yes, but the world is far from ideal ; ). There are some difficulties with internal workbenches (c++). For sure in theory it's possible but complicated. So better use the new workbech-style (or namespace workbenches like currently suggested) wherever possible and hope people at one point see the advantages and working towards consistency.
> 
> > I will soon submit a technical document with:
> > 
> > 1. FreeCAD Extension Development Spec.
> > 2. Migration Guide.
> > 3. Best practices (maybe)
> 
> That sounds promising. There are also others working on this topic (@gbroques).

Totally agree! I think everyone would benefit from the consistency.

More technical documentation on this topic is certainly welcomed. :+1: 

Keep up the great work sir! :smiley:
