### ISSUE TITLE
README Usage section

### ISSUE THREAD

**Issue by luzpaz** [mnesarco/FreeCAD_ExtMan#3]
The README.md should have a Usage section explaining that once the Extension Manager is installed, restart FC and then activate it from the Workbench dropdown menu.

**Comment by mnesarco** [comment]
Ok, Added.

**Comment by luzpaz** [comment]
Perhaps adding this image?  
![image](https://user-images.githubusercontent.com/4140247/93031214-10743580-f5f7-11ea-89b2-1a99edab70d2.png)

**Comment by mnesarco** [comment]
Ok, Done. Thank you.
